Implement reduce method
a-kotova/myArrayLibrary pull request #3
Opened 2022-04-13 14:52 UTC by a-kotova

2022-04-19 08:32 UTC, iharzh requested changes

2022-04-19 08:32 UTC, iharzh commented on index.js
> +  reduce(array, callback, initialValue = null) {
Please provide some error message in case there is no init value

2022-04-20 11:42 UTC, iharzh requested changes

2022-04-20 11:42 UTC, iharzh commented on index.js
> +    try {
`try..catch` block is unnecessary here

2022-04-20 11:42 UTC, iharzh commented on index.js
> +      if (initialValue === undefined) throw new Error();
you can move the error text from `catch` block right inside this error

2022-04-22 09:22 UTC, a-kotova commented on index.js
> +    try {
Removed

2022-04-22 10:20 UTC, iharzh approved these changes

2022-04-22 10:26 UTC, merged